# -*- mode: python ; coding: utf-8 -*-
# Linux onefile spec that avoids bundling system C++ runtime libs which can cause GLIBC mismatches.
import sys
import os
import pathlib
from PyInstaller.utils.hooks import collect_submodules, collect_all

# Read version string generated by build.py (format: MAJOR.MINOR)
_version_file = pathlib.Path('build') / 'VERSION'
_version_str = '0.0'
if _version_file.exists():
    try:
        _version_str = _version_file.read_text(encoding='utf-8').strip()
    except Exception as e:
        print(f"Error reading version from '{_version_file}': {e}. Falling back to default version '{_version_str}'.")

# Base names
_base_exe_name = 'PDF-Toolkit-GUI'

# Compose executable name as: PDF-Toolkit-GUI-<MAJOR>.<MINOR>-linux
try:
    _vparts = [int(p) for p in _version_str.split('.')]
    while len(_vparts) < 2:
        _vparts.append(0)
    _ver_main = f"{_vparts[0]}.{_vparts[1]}"
    _exe_name = f"{_base_exe_name}-{_ver_main}-linux"
except Exception:
    _exe_name = f'{_base_exe_name}-{_version_str}-linux'

# Collect deps
_datas = []
_binaries = []
_hiddenimports = []
_hiddenimports += collect_submodules('PIL')
_fitx = collect_all('fitz')
_datas += _fitx[0]; _binaries += _fitx[1]; _hiddenimports += _fitx[2]


a = Analysis(
    ['pdf_toolkit_gui.py'],
    pathex=[],
    binaries=_binaries,
    datas=_datas,
    hiddenimports=_hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)

# On Linux, drop bundled libstdc++/libgcc so system ones are used at runtime
if sys.platform.startswith('linux'):
    drop = {'libstdc++.so.6', 'libgcc_s.so.1'}
    kept = []
    for name, path, typecode in a.binaries:
        base = os.path.basename(path)
        if base in drop:
            continue
        kept.append((name, path, typecode))
    a.binaries = kept

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name=_exe_name,
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    # No Windows VERSIONINFO on Linux build
)

# No COLLECT: onefile build goes into dist (dist path decided by CLI args).

