# -*- mode: python ; coding: utf-8 -*-
from PyInstaller.utils.hooks import collect_submodules
from PyInstaller.utils.hooks import collect_all

# Read version string generated by build.py (format: MAJOR.MINOR.PATCH.BUILD)
# Falls back to 0.0.0.0 if not present.
import pathlib
_version_file = pathlib.Path('build') / 'VERSION'
_version_str = '0.0'
if _version_file.exists():
    try:
        _version_str = _version_file.read_text(encoding='utf-8').strip()
    except Exception as e:
        print(f"Error reading version from '{_version_file}': {e}. Falling back to default version '{_version_str}'.")

# Base names
_base_exe_name = 'PDF-Toolkit-GUI'

# Compose EXE name as: PDF-Toolkit-GUI-<MAJOR>.<MINOR>-win
try:
    _vparts = [int(p) for p in _version_str.split('.')]
    while len(_vparts) < 4:
        _vparts.append(0)
    _ver_main = f"{_vparts[0]}.{_vparts[1]}"
    _exe_name = f"{_base_exe_name}-{_ver_main}-win"
except Exception:
    # Fallback to previous naming if parsing fails
    _exe_name = f'{_base_exe_name}-{_version_str}-win'


datas = []
binaries = []
hiddenimports = []
hiddenimports += collect_submodules('PIL')
tmp_ret = collect_all('fitz')
datas += tmp_ret[0]; binaries += tmp_ret[1]; hiddenimports += tmp_ret[2]


a = Analysis(
    ['pdf_toolkit_gui.py'],
    pathex=[],
    binaries=binaries,
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name=_exe_name,
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    # Use a generated Windows VERSIONINFO resource file. The build script creates `build/versionfile.txt` and
    # passes its path to PyInstaller when building from this spec.
    version='build/versionfile.txt',
)

# No COLLECT step: we only build the one-file EXE into the dist directory.